[package]
name = "code_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
minijinja = "2.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
